name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/nnewman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run API Tests
        run: newman run RestfulBookerBVT.postman_collection.json -e Production.postman_environment.json
    
